#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Long;
use FindBin qw($Bin);
use GPBgraph;
use GPBarg;
use GPBanno;
use GPBgfa;
use GPBreport;
use GPBpheno;
use GPBbed;

my $usage = "\nUsage:
For variant data: gpb --variant <in.vcf> --ref-fa <ref.fa> --gene-anno <ref_gene.gff3/gtf> (--geneid <ID> | --geneid-list <list.file> | --region <chr:start-end> | --region-list <list.bed>) [OPTIONS]
For pangenome graph: gpb --graph <graph.og> --ref-name <ref_path> --gene-anno <ref_gene.gff3/gtf> (--geneid <ID> | --geneid-list <list.file> | --region <chr:start-end> | --region-list <list.bed>) [OPTIONS]

REQUIRED ARGUMENTS
  1. Input mode (choose one group):
    -v, --variant	<file>		Variants in VCF format (.vcf). (requires '--ref-fa')
    -r, --ref-fa	<file>		Reference genome in FASTA format (.fa). (requires '--variant')

    -g, --graph		<file>		Variation graph in ODGI format (.og). (requires '--ref-name')
    -R, --ref-name	<string>	Name of the reference path in the graph. (requires '--graph')

  2. Reference gene annotation:
    -a, --gene-anno	<file>		Gene annotation file in GFF3/GTF format for the reference genome.	

  3. Analysis range (choose one)
    --geneid		<string>	Single gene ID to analyze.
    --geneid-list	<file>		File containing list of gene IDs (one per line).
    --region		<string>	Single genomic region in 'chr:start-end' format (e.g. chr1:1000-2000).
    --region-list	<file>		BED file with genomic regions (chrom<tab>start<tab>end, 0-based).

OPTIONAL ARGUMENTS
    -x, --extra-anno	<file>		Additional reference-genome annotations besides genes in BED format
    					(e.g. repeats, domains). 
    -p, --pheno		<file>		Tab-delimited phenotype matrix: first column contains path identifiers 
    					(header: 'Path'), remaining columns represent different phenotype with 
					corresponding names as headers.    
					Missing values in the file are indicated by '-', 'NA', 'NaN', 'null', 
					'None',	'NULL', 'undefined', 'unknown' or 'Unknown'.					

    -o, --out		<string>	Output directory name.

    -e, --extend	<n>		Extend analysis region by N bp upstream and downstream of genes.
    					Only work with '--geneid' or '--geneid-list'.
    					(Default:10)

    -d,			<n>		Parameter for 'odgi extract'.
    --max-distance-subpaths		Maximum distance between subpaths allowed for merging them. It reduces
    					the fragmentation of unspecified paths in the input path ranges.
					(Default:10000)

    -m,			<n>		Parameter for 'odgi extract'.
    --max-merging-iterations		Maximum number of iterations in attempting to merge close subpaths. It
    					stops early if during an iteration no subpaths were merged.
					(Default:3)

    -t, --threads	<n>		Thread number.

    -h, --help				Print usage page.

\n";

die $usage if @ARGV<1;

my ($vcf, $reffa, $graph, $refname, $anno);
my ($geneid, $genelist, $region, $regionlist);
my ($bed, $pheno, $out, $help);
my $extend;
my $threads = 1;
my $maxd = 10000;
my $maxe = 3;

GetOptions(
   
   'v|variant=s'	=> \$vcf,
   'r|ref-fa=s'		=> \$reffa,
   'g|graph=s'		=> \$graph,
   'R|ref-name=s'	=> \$refname,

   'a|gene-anno=s'	=> \$anno,

   'geneid=s'		=> \$geneid,
   'geneid-list=s'	=> \$genelist,
   'region=s'		=> \$region,
   'region-list=s'	=> \$regionlist,

   'x|extra-anno=s'	=> \$bed,
   'p|pheno=s'		=> \$pheno,

   'o|out=s'		=> \$out,

   'e|extend=i'		=> \$extend,
   'd|max-distance-subpaths=i'	=> \$maxd,
   'm|max-merging-iterations=i'	=> \$maxe,
   't|threads=i'	=> \$threads,
   'h|help!'		=> \$help

);

die $usage if $help;

my $has_vcf_mode = ($vcf || $reffa);
my $has_graph_mode = ($graph || $refname);

GPBarg::check_input($vcf, $reffa, $graph, $refname, $anno, $geneid, $genelist, $region, $regionlist, $extend, $bed, $pheno, $maxe, $maxd, $threads);

if($has_vcf_mode){
	die "Please install 'vg' first\n" if(system("command -v vg > /dev/null 2>&1") != 0);
	die "Please install 'bcftools' first\n" if(system("command -v bcftools > /dev/null 2>&1") != 0);
	die "Please install 'samtools' first\n" if(system("command -v samtools > /dev/null 2>&1") != 0);
}
die "Please install 'odgi' first\n" if(system("command -v odgi > /dev/null 2>&1") != 0);

if (defined $geneid || defined $genelist) {
	$extend = 10 unless defined $extend;
}

my $dir_name = GPBarg::mk_outdir($out);
my $anno_dir = "gene_anno";
my $graph_dir = "gene_graph";

printLog("Extracting gene annotation information...");
mkdir "${dir_name}/$anno_dir" or die "Cannot create ${dir_name}/$anno_dir: $!\n";
my $interval_arr = GPBanno::get_interval($geneid, $genelist, $region, $regionlist, $extend, $anno, "$dir_name/$anno_dir");

if ($has_vcf_mode) {
	printLog("Constructing pangenome graph with VG...");
	GPBgraph::build_graph($vcf, $reffa, $interval_arr, $dir_name, $threads);
	$graph = "${dir_name}/pan.og";
}

mkdir "${dir_name}/visualization" or die "Cannot create ${dir_name}/visualization: $!\n";
mkdir "${dir_name}/$graph_dir" or die "Cannot create ${dir_name}/$graph_dir: $!\n";

foreach my $interval (@$interval_arr) {
	my ($name, $chr, $start, $end) = @$interval;
	printLog("Processing the '$name' region...");
	my $node_add_sample;
	my $edge_out;
	my $ref_info;
	if ($has_vcf_mode){
		printLog("- Extracting subgraph with ODGI...");
		GPBgraph::extract_subgraph($graph, $chr, "$chr:$start-$end", $dir_name, $graph_dir, $interval->[0], $maxd, $maxe, $threads);
		printLog("- Performing hierarchical layout of the sequence graph and computing coordinates...");
		($node_add_sample, $edge_out, $ref_info) = GPBgfa::parse_variant_gfa("$dir_name/$graph_dir/$name.gfa", "$dir_name/variant_samples.txt", "$dir_name/pan.vcf");
	} elsif ($has_graph_mode) {
		printLog("- Extracting subgraph with ODGI...");
		GPBgraph::extract_subgraph($graph, $refname.".".$chr, "$refname.$chr:$start-$end", $dir_name, $graph_dir, $name, $maxd, $maxe, $threads);
		printLog("- Performing hierarchical layout of the sequence graph and computing coordinates...");
		($node_add_sample, $edge_out, $ref_info) = GPBgfa::parse_graph_gfa("$dir_name/$graph_dir/$name.gfa", $refname);
	}
	if (grep { @$_[2] <= 0 } @$edge_out) {
    		warn "Warning: Complex mutation from overlapping variants in '$name' region exceeds current handling capability.\n";
		next;
	}

	printLog("- Adding gene annotation track...");
	my $format = GPBanno::detect_anno_format($anno);
        my $all_gene_pos = GPBanno::get_gene_pos("$dir_name/$anno_dir/$name.$format");
        my $bed_data;
        if (defined $bed){
                printLog("- Adding additional annotation track...");
                $bed_data = GPBbed::load_bed($bed, $interval);
        } else {
                $bed_data = '';
        }

	my $final_nodes;
	my $pheno_meta;
	if(defined $pheno){
		printLog("- Adding phenotype information tracks...");
		($final_nodes, $pheno_meta) = GPBpheno::add_pheno($node_add_sample, $pheno);
	}else{
		$final_nodes = $node_add_sample;
		$pheno_meta = '';
	}

	printLog("- Generating final visualization...");
	GPBreport::export_figure("${dir_name}/visualization", $interval->[0], $final_nodes, $edge_out, $ref_info, $all_gene_pos, $bed_data, $pheno_meta);
	
}

unlink "$dir_name/variant_samples.txt" if -e "$dir_name/variant_samples.txt";
system "cp -r ${Bin}/src/js ${dir_name}/visualization";
system "cp -r ${Bin}/src/css ${dir_name}/visualization";

sub printLog{
        my ($info) = @_;
	my $ts = qx(date '+%F %T'); chomp $ts;
    	print STDOUT "[ -- $ts -- ] $info\n";
}



